#!/bin/bash

set +e

total=`cat /dev/shm/total`
failed=`cat /dev/shm/failed`

echo "Failed: ${failed}"

if [ "${failed}" != "" ] && [ "${failed}" -gt "0" ]; then
    cmd=("${@}")
    "${cmd[@]}" &
    cmd_pid="${!}"
    wait "${cmd_pid}"
    status="${?}"
fi
