#!/bin/bash

set +e

cmd=("${@}")

echo " "
echo "------------- ↓↓↓ Running: ${cmd[*]}"

"${cmd[@]}" &
cmd_pid="${!}"
wait "${cmd_pid}"
status="${?}"

if [[ "${status}" -eq 0 ]]; then
    echo "------------- ↑↑↑ OK"
else
    echo "------------- ↑↑↑ ${ANSI_RED}ERROR: exited with ${status}${ANSI_RESET}"
    echo "------------- ↑↑↑ ${ANSI_GREY}${cmd[*]}${ANSI_RESET}"
    exit 1
fi
