#!/bin/bash

if [ "$BUDDY_RUN_MODE" = "SCHEDULE" ]; then
  if [ "$PIPELINE_STATUS" = "SUCCESS" ]; then
      curl -X POST --location 'https://slack.com/api/chat.postMessage' \
        -H 'Content-Type: application/json' \
        -H 'Authorization: Bearer '"$SLACK_BOT_TOKEN"'' \
        --data '{
            "channel": "'"$WEEKLY_CI_SLACK_CHANNEL_ID"'",
            "text": ":white_check_mark:The scheduled pipeline *'"$BUDDY_PIPELINE_NAME"'* on the *'"$BUDDY_REPO_SLUG"'* repository succeeded."
        }'
  elif [ "$PIPELINE_STATUS" = "FAILURE" ]; then
      curl -X POST --location 'https://slack.com/api/chat.postMessage' \
        -H 'Content-Type: application/json' \
        -H 'Authorization: Bearer '"$SLACK_BOT_TOKEN"'' \
        --data '{
            "channel": "'"$WEEKLY_CI_SLACK_CHANNEL_ID"'",
            "text": ":x:The scheduled pipeline *'"$BUDDY_PIPELINE_NAME"'* on the *'"$BUDDY_REPO_SLUG"'* repository failed. Manual intervention is required! \n*Details*:  <'"$BUDDY_RUN_URL"'>"
        }'
  fi
fi
