build:
    environment:
        php: '7.4.15'

    dependencies:
        override:
            - composer install --ignore-platform-reqs --no-interaction --no-scripts

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            requires:
                - branch: /^master$|^(bugfix|hotfix|beta)\/.+|^feature\/[a-z]+-\d+\/(master|dev)-.+|^feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master|dev)-.+/
            tests:
                override:
                    - php-scrutinizer-run
